name: atnew
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2025.1.31
  - ld_impl_linux-64=2.43
  - libffi=3.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libsqlite=3.46.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libzlib=1.2.13
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=25.0.1
  - python=3.9.1
  - readline=8.2
  - setuptools=75.8.2
  - sqlite=3.46.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - accelerate==1.4.0
      - aiohappyeyeballs==2.4.8
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - airportsdata==20250224
      - alembic==1.15.1
      - alpaca-eval==0.1.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.1.0
      - auto-gptq==0.7.1
      - banal==1.0.6
      - bitsandbytes==0.45.3
      - blake3==1.0.5
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - compressed-tensors==0.9.3
      - contourpy==1.3.0
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - dataset==1.6.2
      - datasets==3.3.2
      - deepspeed==0.16.4
      - deprecated==1.2.18
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - einops==0.8.1
      - email-validator==2.2.0
      - exceptiongroup==1.3.0
      - fastapi==0.115.12
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - filelock==3.18.0
      - fire==0.7.0
      - fonttools==4.60.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gekko==1.2.1
      - gguf==0.16.3
      - googleapis-common-protos==1.70.0
      - greenlet==3.1.1
      - grpcio==1.71.0
      - h11==0.16.0
      - hf-xet==1.1.2
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.31.4
      - idna==3.10
      - importlib-metadata==8.0.0
      - importlib-resources==6.5.2
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.10.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.7
      - lark==1.2.2
      - llguidance==0.7.24
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.11
      - mako==1.3.9
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mistral-common==1.5.5
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.3
      - numba==0.60.0
      - numpy==1.26.3
      - opacus==1.5.4
      - openai==1.82.0
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.9
      - opt-einsum==3.4.0
      - optimum==1.24.0
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==24.2
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post5
      - peft==0.14.0
      - pillow==11.0.0
      - prometheus-client==0.22.0
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.0
      - protobuf==4.25.7
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pycountry==24.6.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - ray==2.46.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rich-toolkit==0.14.6
      - rouge==1.0.1
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - scipy==1.13.1
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==1.4.54
      - starlette==0.46.2
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.52.3
      - transformers-stream-generator==0.0.5
      - triton==3.2.0
      - typer==0.15.4
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - vllm==0.8.5.post1
      - watchfiles==1.0.5
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.29.post2
      - xgrammar==0.1.18
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
